### ISSUE TITLE
Script cassé depuis la mise à jour de l'éditeur de texte de Roll20

### ISSUE THREAD

**Issue by Ulty** [waibcam/CO-ImportExport#1]
@waibcam : Depuis la mise à jour de l'éditeur de handout par Roll20, le script ne fonctionne plus. En effet, l'éditeur insère maintenant automatiquement des tags supplémentaires (&lt;p&gt; et &lt;/p&gt;).

Au cas où tu ne voudrais plus maintenir ce code (ce serait dommage, mais je sais que ce genre de choses est assez prenant), dis-le moi, j'essaierai de le copier et de le maintenir de mon côté.

**Comment by waibcam** [comment]
Ah merci de me prévenir @Ulty !
Je vais regarder ce que je peux faire pour régler le souci.

**Comment by bertheto** [comment]
Hello Kamille, si tu n'as pas le temps je peux m'en occuper si tu veux.
Ludiquement
Hulkito

**Comment by waibcam** [comment]
OMG J'ai complètement oublié ce souci o-O
J'avoue qu'en ce moment je suis charète niveau timing :/

Un p'tit coup de main ne serait pas de refus :) Sinon ca devra attendre un peu.

**Comment by bertheto** [comment]
hello Kamille, merci pour ta réponse
Par contre je n'ai pas les droits en écriture sur ton repository...
merci d'avance

Hulkito

**Comment by waibcam** [comment]
Je pensais que tu voulais simplement faire un PR non ?

**Comment by waibcam** [comment]
Bon, invitation faite :)

**Comment by bertheto** [comment]
oui mais le push de ma branche est rejeté du fait des droits

**Comment by bertheto** [comment]
ok merci !
