### ISSUE TITLE
Gestion de l'attribut "type_personnage"

### ISSUE THREAD

**Issue by bertheto** [waibcam/CO-ImportExport#3]
Actuellement l'attribut type_personnage n'est pas géré (PJ/PNJ) du coup tous les imports/exports sont de type PJ. Le soucis est que pour un pnj, sur roll20 avec la fiche de perso, quand on bascule sur PNJ, les attaques disparaissent (et inversemment)...
L'attribut type_personnage n'est présent dans l'export que si on modifié la combo dans la fiche de personnage.
![image](https://user-images.githubusercontent.com/9333527/81047834-88995480-8ebb-11ea-854f-aa8d3f2dada0.png)
Il faut donc, si l'attribut est absent, le générer avec comme valeur par défaut PJ.

**Comment by bertheto** [comment]
Je vais fixer le problème et faire une PR.

**Comment by waibcam** [comment]
#4
